apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yoav-klein/argocd
    targetRevision: HEAD
    path: manifests/helm/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
