apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-microservices-application
  namespace: argocd
spec:
  generators:
  - list:
      elements:
          - name: 'foo'
            path: 'manifests/helm/foo'
          - name: 'bar'
            path: 'manifests/helm/bar'
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/yoav-klein/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
            valueFiles:
                - values-prod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argo-demo
