apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yoav-klein/argocd
    targetRevision: {{ .Values.targetRevision }}
    path: manifests/helm/baz
    helm:
        valueFiles:
           - {{ .Values.env }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
