apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yoav-klein/argocd
    targetRevision: {{ .Values.targetRevision }}
    path: manifests/helm/foo
    helm:
        valueFiles:
            - {{ .Values.env }}
        parameters:
            - name: endpoints.kafka
              value: {{ .Values.endpoints.kafka  }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
