kind: Service
apiVersion: v1
metadata:
    name: demo-app
    namespace: argo-demo
spec:
    selector:
        app: demo-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
