kind: Deployment
apiVersion: apps/v1
metadata:
    name: foo
    namespace: argo-demo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: foo
    template:
        metadata:
            labels:
                app: foo
        spec:
            containers:
                - name: foo
                  image: yoavklein3/foo:1.0
                  env:
                     - name: 'ENV'
                       value: 'dev'
                     - name: 'PORT'
                       value: '5000'
                     - name: 'KAFKA_ENDPOINT'
                       value: '1.2.3.4'
                  ports:
                      - containerPort: 5000




