apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yoav-klein/argocd
    targetRevision: HEAD
    path: manifests/foo-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
